name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SQLServer_PASSWORD }}
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/MLOps.NET.sln
    - name: Build
      run: dotnet build src/MLOps.NET.sln --configuration Release --no-restore    
    - name: Tests
      run: dotnet test src/MLOps.NET.sln --configuration Release --no-restore --no-build --filter TestCategory=Integration  
